class config:
    STEERING_RC_GPIO = 26
    THROTTLE_RC_GPIO = 20
    DATA_WIPER_RC_GPIO = 19
    PIGPIO_STEERING_MID = 1500
    PIGPIO_MAX_FORWARD = 2000
    PIGPIO_STOPPED_PWM = 1500
    PIGPIO_MAX_REVERSE = 1000
    AUTO_RECORD_ON_THROTTLE = False
    PIGPIO_INVERT = False
    PIGPIO_JITTER = 0.025